<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
use Carbon\Carbon;
class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        DB::table('users')->insert(
            [
                'Email'=>'pacjenttest@gmail.com',
                'Password'=>bcrypt('12345'),
                'First_name'=>'Pacjent',
                'Last_name'=>'Testowy',
                'Sex'=>'0',
                'Birthday'=>Carbon::parse('1967-07-19'),
                'Role_id'=>'2',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'aluthwood1@hibu.com',
                'Password'=>bcrypt('J3xbThnuq'),
                'First_name'=>'Adriano',
                'Last_name'=>'Luthwood',
                'Sex'=>'0',
                'Birthday'=>Carbon::parse('1999-01-16'),
                'Role_id'=>'3',
                'updated_info'=>'3',
                'updated_at'=>'2021-12-22',
                'created_at'=>'2021-10-08'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'sbromby2@yelp.com',
                'Password'=>bcrypt('i61OxBrOQDPe'),
                'First_name'=>'Sanson',
                'Last_name'=>'Bromby',
                'Sex'=>'0',
                'Birthday'=>Carbon::parse('1993-01-11'),
                'Role_id'=>'1',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-17',
                'created_at'=>'2021-10-14'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'ehodges3@wiley.com',
                'Password'=>bcrypt('hW5BToiXc7'),
                'First_name'=>'Elvera',
                'Last_name'=>'Hodges',
                'Sex'=>'1',
                'Birthday'=>Carbon::parse('1961-07-14'),
                'Role_id'=>'2',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-11',
                'created_at'=>'2021-10-16'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'cpetrolli4@oaic.gov.au',
                'Password'=>bcrypt('kq90I8qD'),
                'First_name'=>'Cleveland',
                'Last_name'=>'Petrolli',
                'Sex'=>'1',
                'Birthday'=>Carbon::parse('1959-08-17'),
                'Role_id'=>'2',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-16',
                'created_at'=>'2021-10-23'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'amarriner5@canalblog.com',
                'Password'=>bcrypt('QnxvKe'),
                'First_name'=>'Anjanette',
                'Last_name'=>'Marriner',
                'Sex'=>'1',
                'Birthday'=>Carbon::parse('1970-03-07'),
                'Role_id'=>'2',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-01',
                'created_at'=>'2021-10-08'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'eaugie6@home.pl',
                'Password'=>bcrypt('9d8k1P2lIIw'),
                'First_name'=>'Emile',
                'Last_name'=>'Augie',
                'Sex'=>'1',
                'Birthday'=>Carbon::parse('1974-03-28'),
                'Role_id'=>'2',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-01',
                'created_at'=>'2021-10-27'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'pannand7@ucla.edu',
                'Password'=>bcrypt('nG9NMuf21J'),
                'First_name'=>'Petr',
                'Last_name'=>'Annand',
                'Sex'=>'0',
                'Birthday'=>Carbon::parse('1992-12-12'),
                'Role_id'=>'2',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-21',
                'created_at'=>'2021-10-30'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'tside8@furl.net',
                'Password'=>bcrypt('UiRMVrjr'),
                'First_name'=>'Tommie',
                'Last_name'=>'Side',
                'Sex'=>'0',
                'Birthday'=>Carbon::parse('1976-11-18'),
                'Role_id'=>'2',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-19',
                'created_at'=>'2021-10-16'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'mtribble9@indiegogo.com',
                'Password'=>bcrypt('qujYR6NTT3Wq'),
                'First_name'=>'Marena',
                'Last_name'=>'Tribble',
                'Sex'=>'1',
                'Birthday'=>Carbon::parse('1996-12-27'),
                'Role_id'=>'2',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-22',
                'created_at'=>'2021-10-08'
            ]);
        // ksvivbskbvsdkdvbsjhvdbdvbjhvd
        DB::table('users')->insert(
            [
                'Email'=>'admin@gmail.com',
                'Password'=>bcrypt('12345'),
                'First_name'=>'Admin',
                'Last_name'=>'Testowy',
                'Sex'=>'0',
                'Birthday'=>Carbon::parse('1985-07-19'),
                'Role_id'=>'1',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-10-01'
            ]);
            DB::table('users')->insert(
            [
                'Email'=>'doktortest@gmail.com',
                'Password'=>bcrypt('12345'),
                'First_name'=>'Doktor',
                'Last_name'=>'Testowy',
                'Sex'=>'0',
                'Birthday'=>Carbon::parse('1967-07-18'),
                'Role_id'=>'3',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-10-01'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'kmingardi0@jugem.jp',
                'Password'=>bcrypt('ATqm4vjs4'),
                'First_name'=>'Klarika',
                'Last_name'=>'Mingardi',
                'Sex'=>'1',
                'Birthday'=>Carbon::parse('1979-06-10'),
                'Role_id'=>'3',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-13',
                'created_at'=>'2021-10-01'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'bsalazar2@sciencedaily.com',
                'Password'=>bcrypt('Q8J9Jnq'),
                'First_name'=>'Benedikta',
                'Last_name'=>'Salazar',
                'Sex'=>'1',
                'Birthday'=>Carbon::parse('1973-01-15'),
                'Role_id'=>'3',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-17',
                'created_at'=>'2021-10-01'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'ebeer4@mashable.com',
                'Password'=>bcrypt('GNPPB1FtY3'),
                'First_name'=>'Edith',
                'Last_name'=>'Beer',
                'Sex'=>'0',
                'Birthday'=>Carbon::parse('1971-07-16'),
                'Role_id'=>'3',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-11',
                'created_at'=>'2021-10-01'
            ]);
        DB::table('users')->insert(
            [
                'Email'=>'lhaggard3@creativecommons.org',
                'Password'=>bcrypt('yYaa9lg3n'),
                'First_name'=>'Lanna',
                'Last_name'=>'Haggard',
                'Sex'=>'1',
                'Birthday'=>Carbon::parse('1969-04-19'),
                'Role_id'=>'3',
                'updated_info'=>'1',
                'updated_at'=>'2021-12-16',
                'created_at'=>'2021-10-01'
            ]);
    }
}
