<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class VisitsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('visits')->insert(
            [
                'User_id'=>'7',
                'Doctor_id'=>'1',
                'Visit_time'=>'07:00',
                'Visit_date'=>'2021-10-15',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'9',
                'Doctor_id'=>'1',
                'Visit_time'=>'09:00',
                'Visit_date'=>'2021-10-24',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'11',
                'Doctor_id'=>'1',
                'Visit_time'=>'11:00',
                'Visit_date'=>'2022-02-10',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'7',
                'Doctor_id'=>'1',
                'Visit_time'=>'13:00',
                'Visit_date'=>'2022-02-15',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'12',
                'Doctor_id'=>'1',
                'Visit_time'=>'11:00',
                'Visit_date'=>'2022-03-05',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'7',
                'Doctor_id'=>'2',
                'Visit_time'=>'12:00',
                'Visit_date'=>'2021-10-20',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'8',
                'Doctor_id'=>'2',
                'Visit_time'=>'20:00',
                'Visit_date'=>'2021-10-27',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'14',
                'Doctor_id'=>'2',
                'Visit_time'=>'15:00',
                'Visit_date'=>'2022-02-17',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'7',
                'Doctor_id'=>'2',
                'Visit_time'=>'17:00',
                'Visit_date'=>'2022-02-25',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'15',
                'Doctor_id'=>'2',
                'Visit_time'=>'19:00',
                'Visit_date'=>'2022-03-15',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'7',
                'Doctor_id'=>'3',
                'Visit_time'=>'11:00',
                'Visit_date'=>'2021-11-20',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'10',
                'Doctor_id'=>'3',
                'Visit_time'=>'19:00',
                'Visit_date'=>'2021-11-27',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'13',
                'Doctor_id'=>'3',
                'Visit_time'=>'17:00',
                'Visit_date'=>'2022-03-17',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'7',
                'Doctor_id'=>'3',
                'Visit_time'=>'18:00',
                'Visit_date'=>'2022-03-25',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'16',
                'Doctor_id'=>'3',
                'Visit_time'=>'19:00',
                'Visit_date'=>'2022-03-10',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'7',
                'Doctor_id'=>'4',
                'Visit_time'=>'10:00',
                'Visit_date'=>'2021-11-10',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'12',
                'Doctor_id'=>'4',
                'Visit_time'=>'18:00',
                'Visit_date'=>'2021-11-19',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'15',
                'Doctor_id'=>'4',
                'Visit_time'=>'11:00',
                'Visit_date'=>'2022-03-17',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'7',
                'Doctor_id'=>'4',
                'Visit_time'=>'18:00',
                'Visit_date'=>'2022-03-22',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'16',
                'Doctor_id'=>'4',
                'Visit_time'=>'14:00',
                'Visit_date'=>'2022-03-16',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'7',
                'Doctor_id'=>'5',
                'Visit_time'=>'10:00',
                'Visit_date'=>'2021-10-10',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'8',
                'Doctor_id'=>'5',
                'Visit_time'=>'18:00',
                'Visit_date'=>'2021-10-09',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'9',
                'Doctor_id'=>'5',
                'Visit_time'=>'11:00',
                'Visit_date'=>'2022-03-04',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'7',
                'Doctor_id'=>'5',
                'Visit_time'=>'18:00',
                'Visit_date'=>'2022-03-02',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
        DB::table('visits')->insert(
            [
                'User_id'=>'14',
                'Doctor_id'=>'5',
                'Visit_time'=>'14:00',
                'Visit_date'=>'2022-03-06',
                'updated_at'=>'2021-12-06',
                'created_at'=>'2021-11-24'
            ]);
    }
}
